### ISSUE TITLE
Excellent work! Would it be possible for you to mention our IPDreamer in the README?

### ISSUE THREAD

**Issue by zengbohan0217** [MrTornado24/DreamCraft3D_Plus#4]
Dear authors,

Thank you very much for publishing such a high-quality paper. At the same time, we have a humble request. About a year ago, we uploaded an IPDreamer (https://arxiv.org/pdf/2310.05375), demonstrating the significant contribution of image prompt adaptation to 3D generation just as the DreamCraft3D++. Therefore, we believe that DreamCraft3D++ is extremely solid. We would sincerely appreciate it if you could consider adding a reference to IPDreamer in the README. If you are willing to include it, we would be very grateful.

**Comment by MrTornado24** [comment]
Hi Bohan, thanks for your reminder! The link is added now.

**Comment by zengbohan0217** [comment]
Thank you very, very much. I hope that image prompt adaptation can contribute to the further development of the 3D community. I am also deeply grateful for the inspiration brought to researchers by Dreamcraft3D and Dreamcraft3D++.
